{% set name = "oras-py" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oras-project/oras-py/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7261e6f1924acf09c9e086da024e0975036e96df1beceb2235cffadef455fd07

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - oras-py=oras.cli:run

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - jsonschema
    - requests
    - docker-py ==5.0.1

test:
  requires:
    - pip
  imports:
    - oras
  commands:
    - pip check
    - oras-py --help

about:
  home: https://github.com/oras-project/oras-py
  license: Apache-2.0
  license_file: LICENSE
  summary: OCI Registry as Storage Python client
  doc_url: https://oras-project.github.io/oras-py
  dev_url: https://github.com/oras-project/oras-py

  description: |
    OCI Registry as Storage (ORAS) enables client libraries to push OCI Artifacts to OCI Conformant registries.
    This is a Python client for these interactions.

extra:
  recipe-maintainers:
    - vsoch
    - wolfv
