{% set name = "oras-py" %}
{% set version = "0.2.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oras-project/oras-py/archive/refs/tags/{{ version }}.tar.gz
  sha256: b56a6c4ad6488d8ab786912219f1467d205061e178b0350373dbdb250e476e42

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
  run:
    - python >={{ python_min }}
    - jsonschema
    - requests

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - oras
  commands:
    - pip check

about:
  home: https://github.com/oras-project/oras-py
  license: Apache-2.0
  license_file: LICENSE
  summary: OCI Registry as Storage Python client
  doc_url: https://oras-project.github.io/oras-py
  dev_url: https://github.com/oras-project/oras-py

  description: |
    OCI Registry as Storage (ORAS) enables client libraries to push OCI Artifacts to OCI Conformant registries.
    This is a Python client for these interactions.

extra:
  recipe-maintainers:
    - vsoch
    - wolfv
