{% set name = "oras-py" %}
{% set version = "0.1.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oras-project/oras-py/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5c7aa89e37c6d301374f7ebfa348d269b03867f9a930fa3baed6bf89f8b2e7c8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - jsonschema
    - requests

test:
  requires:
    - pip
  imports:
    - oras
  commands:
    - pip check

about:
  home: https://github.com/oras-project/oras-py
  license: Apache-2.0
  license_file: LICENSE
  summary: OCI Registry as Storage Python client
  doc_url: https://oras-project.github.io/oras-py
  dev_url: https://github.com/oras-project/oras-py

  description: |
    OCI Registry as Storage (ORAS) enables client libraries to push OCI Artifacts to OCI Conformant registries.
    This is a Python client for these interactions.

extra:
  recipe-maintainers:
    - vsoch
    - wolfv
