{% set name = "oras-py" %}
{% set version = "0.2.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oras-project/oras-py/archive/refs/tags/{{ version }}.tar.gz
  sha256: a47e6fb15b8a8fee384ab4ac37b401a43274da13557e3e6c5ad3e70ba9e2cadf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
  run:
    - python >={{ python_min }}
    - jsonschema
    - requests

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - oras
  commands:
    - pip check

about:
  home: https://github.com/oras-project/oras-py
  license: Apache-2.0
  license_file: LICENSE
  summary: OCI Registry as Storage Python client
  doc_url: https://oras-project.github.io/oras-py
  dev_url: https://github.com/oras-project/oras-py

  description: |
    OCI Registry as Storage (ORAS) enables client libraries to push OCI Artifacts to OCI Conformant registries.
    This is a Python client for these interactions.

extra:
  recipe-maintainers:
    - vsoch
    - wolfv
